adminapp/urls.py
from django.urls import path, include
from . import views
from .views import datetimepagecall

urlpatterns =[
    path('', views.projecthomepage, name='ProjectHomePage'),
    path('printpagecall/',views.printpagecall,name='printpagecall'),
    path('printpagelogic/',views.printpagelogic,name='printpagelogic'),
    path('exceptionpagecall/',views.exceptionpagecall,name='exceptionpagecall'),
    path('exceptionpagelogic/',views.exceptionpagelogic,name='exceptionpagelogic'),
    path('randompagecall/',views.randompagecall,name='randompagecall'),
    path('randomlogic/',views.randomlogic,name='randomlogic'),
    path('calculator/',views.calculator,name='calculator'),
    path('calculatorlogic/',views.calculatorlogic,name='calculatorlogic'),
    path('add_task/',views.add_task,name='add_task'),
    path('<int:pk>/delete/',views.delete_task,name='delete_task'),
    path('loginpage/',views.loginpage,name='loginpage'),
    path('datetimepagecall/',views.datetimepagecall,name='datetimepagecall'),
    path('datetimepagelogic/',views.datetimepagelogic,name='datetimepagelogic'),
    path('RegisterPageCall/',views.RegisterPageCall,name='RegisterPageCall'),
    path('RegisterLogic/',views.RegisterLogic,name='RegisterLogic'),
    path('logout/',views.logout,name='logout'),
    path('UserLoginPageCall/',views.UserLoginPageCall,name='UserLoginPageCall'),
    path('UserLoginLogic/',views.UserLoginLogic,name='UserLoginLogic'),
    path('add_student/',views.add_student,name='add_student'),
    path('add_studentpagecall/',views.add_studentpagecall,name='add_studentpagecall'),
    path('student_list/',views.student_list,name='student_list'),
    path('submit_feedback', views.feedback_form, name='submit_feedback'),
]

facultyapp/urls.py
from django.urls import path
from . import views

app_name = 'facultyapp'

urlpatterns = [
    path('facultypagecall/', views.facultypagecall, name='FacultyHomePage'),
    path('add_course/', views.add_course, name='add_course'),
    path('view_student_list/', views.view_student_list, name='view_student_list'),
    path('add_blog/', views.add_blog, name='add_blog'),
    path('<int:pk>/delete/', views.delete_task, name='delete'),
    path('post_marks/', views.post_marks, name='post_marks'),
]

studentmanagementsystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('studentapp/', include('studentapp.urls', namespace='studentapp')),
    path('facultyapp/', include('facultyapp.urls', namespace='facultyapp')),
    path('', include('adminapp.urls')),
]

templates/Navbar/FacultyNavbar.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'facultyapp:FacultyHomePage' %}">Faculty Portal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'facultyapp:FacultyHomePage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:add_course' %}">ADD Course</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:add_blog' %}">Blog_post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:post_marks' %}">Post marks</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:view_student_list' %}">View student</a>
        </li>
      </ul>
    </div>
    <ul class="navbar-nav ms-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="nav-link">Welcome, {{ user.username }}</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}"><b><i>Logout</i></b></a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'registerpagecall' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'loginpagecall' %}">Login</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/Navbar/ProjectNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'ProjectHomePage' %}" style="color:orange">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ol class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'add_studentpagecall' %}" style="color:orange">Add student</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'student_list' %}" style="color:orange">student list</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color:orange;">
            PFSD concepts
          </a>
          <ol class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">print_to_console</a></li>
            <li><a class="dropdown-item" href="{% url 'exceptionpagecall' %}">Exception</a></li>
            <li><a class="dropdown-item" href="{% url 'randompagecall' %}"> Random generator</a></li>
            <li><a class="dropdown-item" href="{% url 'calculator' %}"> Simple calculator</a></li>
            <li><a class="dropdown-item" href="{% url 'add_task' %}"> To_Do_List</a></li>
            <li><a class="dropdown-item" href="{% url 'datetimepagelogic' %}"> Date_Time</a></li>
              <li><a class="dropdown-item" href="{% url 'submit_feedback' %}"> Feedback</a></li>
          </ol>
        </li>
    </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}" >Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'RegisterPageCall' %}" style="color:orange">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'loginpage' %}" style="color:orange">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

templates/Navbar/StudentNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-success">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'ProjectHomePage' %}">Student</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>

      </ul>
    </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}"><b><i>Logout</i></b></a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}

</body>
</html>